# Generated by Django 3.0.14 on 2022-09-11 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username_changed', models.DateField(blank=True, null=True, verbose_name='username_changed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_info', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Meta Info',
                'verbose_name_plural': 'User Meta Info',
            },
        ),
    ]
