# Generated by Django 3.0.14 on 2022-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetainfo',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='dob_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='is_requesting_delete',
            field=models.BooleanField(default=False),
        ),
    ]
