# Generated by Django 3.1.14 on 2022-11-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tag Type',
                'verbose_name_plural': 'Tag Types',
            },
        ),
    ]
