# Generated by Django 3.1.14 on 2022-11-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=15)),
                ('archive_posts', models.BooleanField(default=False, help_text='Posts after a period of X months will be archived automatically')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
