# Generated by Django 3.1.14 on 2022-11-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_added_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rule_type', models.CharField(choices=[('POSTS', 'Posts'), ('COMMENTS', 'Comments'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='groups.group')),
            ],
            options={
                'verbose_name': 'Group Rule',
                'verbose_name_plural': 'Group Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
