# Generated by Django 3.1.14 on 2022-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_added_type_in_tag'),
        ('groups', '0005_added_group_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='groups', to='tags.Tag', verbose_name='topics'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='\n            PUBLIC: Anyone can view, post, and comment to this community.<br>\n            RESTRICTED: Anyone can view this community, but only approved users can post.<br>\n            PRIVATE: Only approved users can view and submit to this community.\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('MEMBER', 'Member')], default='MEMBER', help_text='\n            ADMIN: Has (all)permissions to add or remove members as moderators, ban or mute members.<br>\n            MODERATOR: Has permission to add, remove, ban or mute members.<br>\n            MEMBER: Can post, like, comment, share, bookmark group posts.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BANNED', 'Banned'), ('MUTED', 'Muted')], default='ACTIVE', help_text='\n            ACTIVE: Can be active in a group within permissions.<br>\n            MUTED: Forbidden for any activity(post, comment etc) in a group for a week.<br>\n            BANNED: Forbidden for any activity in a group forever\n        ', max_length=10),
        ),
    ]
