# Generated by Django 3.1.14 on 2022-11-21 12:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
        migrations.CreateModel(
            name='PostCommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcommentvote_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Comment Vote',
                'verbose_name_plural': 'Post Comment Votes',
                'ordering': ['created_at'],
            },
        ),
    ]
